name: Test Dispatch
on:
  workflow_dispatch:
    inputs:
      test:
        description: "test"
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.test }}"
